# Site
name: 'Donal Tran Home'
description: 'Persoal Sites. Where I write and post all blogs'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    donald:
      name:           Donald
      site:           https://www.linkedin.com/in/doai-tran-nguyen-van-b125b051/
      avatar:         assets/images/avatar1.jpeg
      bio:            "Hi, I am Donald (Doai Tran), the author of Testing4Everyone. I hope you like it!"
      email:          doai.tran@gmail.com
      youtube:        https://www.youtube.com/@testing4everyone

    testing4everyone:
      name:           Testing4Everyone
      site:           https://josdoaitran.github.io
      avatar:         assets/images/avatar2.png
      bio:            "Blogger account, Youtuber account, who Donald wrote on my morning coffee!"
      email:          fakemail@gmail.com
      youtube:        https://www.youtube.com/@testing4everyone
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: donald
      avatar: /assets/images/avatar1.jpeg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]